import type { PaintTool } from '../paint/types'

/** Spoken word -> tool. Used only to build typed commands, never to dispatch freely. */
export const TOOL_ALIASES: Readonly<Record<string, PaintTool>> = {
  pencil: 'pencil',
  pen: 'pencil',
  brush: 'pencil',
  eraser: 'eraser',
  erase: 'eraser',
  rubber: 'eraser',
  line: 'line',
  rectangle: 'rectangle',
  rect: 'rectangle',
  box: 'rectangle',
  square: 'rectangle',
  ellipse: 'ellipse',
  oval: 'ellipse',
  circle: 'ellipse',
  // Telugu (script)
  వృత్తం: 'ellipse',
  గుండ్రం: 'ellipse',
  దీర్ఘవృత్తం: 'ellipse',
  దీర్ఘచతురస్రం: 'rectangle',
  చతురస్రం: 'rectangle',
  గీత: 'line',
  రేఖ: 'line',
  పెన్సిల్: 'pencil',
  బ్రష్: 'pencil',
  ఎరేజర్: 'eraser',
  టెక్స్ట్: 'text',
  // Romanised Telugu
  vruttham: 'ellipse',
  vrutham: 'ellipse',
  vruttam: 'ellipse',
  gundram: 'ellipse',
  chathurasram: 'rectangle',
  chadaram: 'rectangle',
  githa: 'line',
  rekha: 'line',
  pensil: 'pencil',
  erejar: 'eraser',
  text: 'text',
}

/** Spoken colour name -> hex value accepted by the engine. */
export const COLOR_NAMES: Readonly<Record<string, string>> = {
  red: '#ef4444',
  blue: '#3b82f6',
  green: '#22c55e',
  yellow: '#eab308',
  orange: '#f97316',
  purple: '#8b5cf6',
  pink: '#ec4899',
  brown: '#8b5a2b',
  black: '#000000',
  white: '#ffffff',
  gray: '#78716c',
  grey: '#78716c',
  cyan: '#06b6d4',
  teal: '#14b8a6',
  magenta: '#d946ef',
  // Telugu (script)
  ఎరుపు: '#ef4444',
  నీలం: '#3b82f6',
  ఆకుపచ్చ: '#22c55e',
  పసుపు: '#eab308',
  నారింజ: '#f97316',
  ఊదా: '#8b5cf6',
  గులాబీ: '#ec4899',
  గోధుమ: '#8b5a2b',
  నలుపు: '#000000',
  తెలుపు: '#ffffff',
  బూడిద: '#78716c',
  బంగారు: '#eab308',
  // Romanised Telugu
  erupu: '#ef4444',
  nilam: '#3b82f6',
  pachha: '#22c55e',
  pasupu: '#eab308',
  narimja: '#f97316',
  ooda: '#8b5cf6',
  gulaabi: '#ec4899',
  godhuma: '#8b5a2b',
  nalupu: '#000000',
  telupu: '#ffffff',
  burida: '#78716c',
}

/** Example phrases shown in the in-app "What can I say?" help. */
export const COMMAND_EXAMPLES: readonly string[] = [
  'use pencil',
  'switch to eraser',
  'draw a circle and fill it red',
  'draw a rectangle',
  'fill it blue',
  'use the red brush',
  'set color to red',
  'set brush size to 8',
  'make the brush smaller',
  'undo',
  'redo',
  'clear canvas',
  'export PNG',
  'what can I say?',
  'వృత్తం గీయి మరియు ఎరుపు నింపు',
  'vrutham geyyi mariyu erupu nimpu',
]
